'use strict';
function renderBillingPage() {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Suscripciones · Asisto</title>
<style>
:root{font:14px/1.5 system-ui,sans-serif;color:#102d4b;background:#f3f7fb}*{box-sizing:border-box}body{margin:0}main{max-width:1420px;margin:auto;padding:24px}header,.bar,.actions{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}h1{font-size:28px;margin:0}h2{font-size:18px;margin:0 0 12px}p{margin:5px 0 16px;color:#5b6f86}a{color:#1269a3}.notice{padding:16px;background:#fff6df;border:1px solid #f0d38c;border-radius:12px;margin:20px 0}.card{background:white;border:1px solid #dbe5ef;border-radius:16px;padding:20px;margin:16px 0}.badge{padding:5px 10px;border-radius:20px;background:#e8f4f2;color:#086a61;display:inline-block}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.steps b{display:block}.steps small{color:#5b6f86}input,button{font:inherit;border:1px solid #bccddc;border-radius:8px;padding:9px 12px}input{width:100%;min-width:0;background:white;color:inherit}button{cursor:pointer;color:#123d64;background:#fff}button.primary{background:#1269a3;border-color:#1269a3;color:white}button:disabled{cursor:not-allowed;opacity:.5}label{display:grid;gap:5px;font-size:12px;color:#5b6f86}.accounts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.account{margin:0}.fields{display:grid;grid-template-columns:2fr 1fr;gap:12px;margin:15px 0}.actions{justify-content:flex-start;gap:8px}.state{margin:12px 0;color:#5b6f86}#status{min-height:24px;white-space:pre-wrap}#payments{overflow-x:auto}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:10px;border-bottom:1px solid #e3ebf1}summary{cursor:pointer;font-weight:600}code{font-size:12px}.bar input{max-width:300px}.error{color:#a33221}@media(max-width:800px){main{padding:14px}.accounts,.steps{grid-template-columns:1fr}.fields{grid-template-columns:1fr}}
</style></head><body><main>
<header><div><h1>Suscripciones y cobros</h1><p>Preparación de la adhesión mensual de clientes a Mercado Pago.</p></div><a href="/admin/token-control">Volver a Control de Consumos</a></header>
<div class="notice"><b>Preparación / pruebas — sin débitos reales.</b> Guardar la configuración no suscribe ni cobra al cliente. El cierre de consumos variables y la programación de débitos todavía no están habilitados.</div>
<section class="steps"><div class="card"><b>1. Configurar cliente</b><small>Un titular con todos sus dominios asociados.</small></div><div class="card"><b>2. Probar adhesión</b><small>Exclusivamente con comprador y vendedor de prueba.</small></div><div class="card"><b>3. Cierre mensual · pendiente</b><small>Congelar consumos y dólar oficial antes de habilitar cobros.</small></div></section>
<section class="card"><h2>Estado de la integración</h2><div id="integration">Consultando…</div><details style="margin-top:12px"><summary>Configuración técnica</summary><p>Las credenciales se configuran únicamente en el servidor AWS, nunca en este formulario.</p><code>MP_SUBSCRIPTIONS_MODE=test<br>MP_SUBSCRIPTIONS_ACCESS_TOKEN<br>MP_SUBSCRIPTIONS_WEBHOOK_SECRET<br>MP_SUBSCRIPTIONS_TEST_PAYER_ID<br>MP_SUBSCRIPTIONS_PUBLIC_URL</code><p>Webhook: <code>/webhooks/mercadopago/subscriptions</code>. No existe un modo de cobro productivo en esta etapa.</p></details></section>
<div class="bar"><h2>Clientes facturables</h2><input id="search" aria-label="Buscar cliente" placeholder="Buscar titular o dominio asociado"><button id="reload">Actualizar estados guardados</button></div>
<p id="status" role="status" aria-live="polite"></p><section id="accounts" class="accounts"></section>
<section class="card"><h2>Últimos pagos de prueba</h2><p>Estados confirmados consultando Mercado Pago. Una adhesión autorizada no equivale a un pago aprobado. Estos movimientos no cancelan consumos reales.</p><div id="payments"></div></section>
</main><script>
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={creating:'Alta en curso',unknown:'Alta incierta: consultar antes de reintentar',pending:'Pendiente de autorización',authorized:'Adhesión autorizada (no es pago)',paused:'Pausada',cancelled:'Cancelada',approved:'Aprobado',rejected:'Rechazado',in_process:'En proceso',refunded:'Reembolsado',charged_back:'Contracargo',review:'Requiere revisión'};
let data=null,busy=false;
async function api(path,method='GET',body){const r=await fetch(path,{method,credentials:'same-origin',headers:{'X-Asisto-Billing':'1',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok)throw Error(j.error||'No se pudo completar la operación.');return j;}
function status(message,error=false){$('status').textContent=message;$('status').className=error?'error':'';}
function render(){if(!data)return;const q=$('search').value.trim().toUpperCase(),cfg=data.integration;
 $('integration').textContent=(cfg.testReady?'Lista para probar adhesiones por ARS '+cfg.testAmountArs+'.':'Pruebas bloqueadas: falta configuración del servidor.')+' Débitos reales: deshabilitados.';
 $('accounts').innerHTML=data.accounts.filter(a=>(a.owner+' '+a.company+' '+a.domains.join(' ')).toUpperCase().includes(q)).map(a=>{const p=a.profile||{},s=a.subscription;return '<article class="card account" data-owner="'+esc(a.owner)+'"><h2>'+esc(a.owner)+' · '+esc(a.company)+'</h2><span class="badge">'+esc(a.domains.join(' + '))+'</span><p>Período mensual calendario · Consumo variable · Pesos argentinos</p><div class="fields"><label>Email de facturación<input name="billingEmail" type="email" maxlength="254" value="'+esc(p.billingEmail||'')+'"></label><label>Día previsto de cobro<input name="collectionDay" type="number" min="1" max="28" value="'+esc(p.collectionDay||5)+'"></label></div><p>El día es una previsión guardada, no una orden de débito.</p><div class="actions"><button class="primary" data-action="save">Guardar configuración</button></div><div class="state">Prueba: '+esc(s?(labels[s.status]||s.status):'Sin adhesión')+'</div><div class="actions"><button data-action="test-subscription" '+(!cfg.testReady||!!s||!a.profile?'disabled':'')+'>Crear adhesión de prueba</button>'+(s?'<button data-action="reconcile" '+(!cfg.testReady?'disabled':'')+'>Consultar en Mercado Pago</button><button data-action="cancel-test" '+(!cfg.testReady||s.status==='cancelled'?'disabled':'')+'>Cancelar prueba</button>':'')+(s&&s.checkoutUrl?'<a href="'+esc(s.checkoutUrl)+'" target="_blank" rel="noopener noreferrer">Abrir adhesión de prueba</a>':'')+'</div></article>';}).join('')||'<p>No se encontraron clientes.</p>';
 $('payments').innerHTML=data.payments.length?'<table><thead><tr><th>Cliente</th><th>Estado</th><th>Importe de prueba</th><th>Actualizado</th></tr></thead><tbody>'+data.payments.map(p=>'<tr><td>'+esc(p.owner)+'</td><td>'+esc(labels[p.status]||p.status)+'</td><td>'+esc(p.currency)+' '+esc(p.amount)+'</td><td>'+esc(new Date(p.providerUpdatedAt).toLocaleString('es-AR'))+'</td></tr>').join('')+'</tbody></table>':'<p>No hay pagos de prueba confirmados.</p>';
}
async function load(){data=await api('/api/billing/accounts');render();}
$('search').addEventListener('input',()=>{if(!busy)render();});
$('reload').addEventListener('click',async()=>{if(busy)return;try{await load();status('Datos actualizados.');}catch(e){status(e.message,true);}});
$('accounts').addEventListener('click',async event=>{const button=event.target.closest('button[data-action]');if(!button||busy)return;const card=button.closest('[data-owner]'),owner=card.dataset.owner,action=button.dataset.action;
 if(action==='test-subscription'&&!confirm('Crear una adhesión de PRUEBA por ARS 10 mensuales con las cuentas de prueba del servidor. No se enviará nada al cliente. ¿Continuar?'))return;
 if(action==='cancel-test'&&!confirm('¿Cancelar la adhesión de prueba de '+owner+'?'))return;
 busy=true;button.disabled=true;status('Procesando…');try{const path='/api/billing/accounts/'+encodeURIComponent(owner);await api(path+(action==='save'?'':'/'+action),action==='save'?'PUT':'POST',action==='save'?{billingEmail:card.querySelector('[name=billingEmail]').value,collectionDay:Number(card.querySelector('[name=collectionDay]').value)}:{});await load();status(action==='save'?'Configuración guardada. No se generó ningún débito.':'Estado de la prueba actualizado.');}catch(e){status(e.message,true);}finally{busy=false;button.disabled=false;}});
load().catch(e=>status(e.message,true));
</script></body></html>`;
}
module.exports = { renderBillingPage };
