const express = require("express");
const { ObjectId } = require("mongodb");
const { getDb } = require("./db");

const DEFAULT_SECTORS = [
  { id: "ferreteria", name: "Ferretería", prefix: "F" },
  { id: "herrajes", name: "Herrajes", prefix: "H" },
  { id: "buloneria", name: "Bulonería", prefix: "B" },
  { id: "caja", name: "Caja", prefix: "C" },
  { id: "retiro", name: "Retiro de pedidos", prefix: "R" },
];

const DEFAULT_BANNERS = [
  "https://acdn-us.mitiendanube.com/stores/006/162/992/themes/amazonas/1-slide-1786043920585-7689600605-7fb70c00de38f8b949bb2fde436d37ea1786043922-1024-1024.jpg?4168203849057930746",
  "https://acdn-us.mitiendanube.com/stores/006/162/992/themes/amazonas/2-slide-1786043506674-1649773286-25b60bcb6943aefb2090146894c9d01d1786043508-1024-1024.webp?4168203849057930746",
  "https://acdn-us.mitiendanube.com/stores/006/162/992/themes/amazonas/2-slide-1786033458293-4286066824-123e73ebea9fe0598db5eccf0ab902ba1786033459-1024-1024.webp?4168203849057930746",
];

function clean(value, max = 80) { return String(value || "").trim().slice(0, max); }
function tenant(value) { return clean(value, 60).toUpperCase().replace(/[^A-Z0-9_-]/g, ""); }
function dayKey() { return new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires" }).format(new Date()); }
function ticketView(t, ahead, current) {
  return { id: String(t._id), displayNumber: t.displayNumber, status: t.status, sectorId: t.sectorId,
    sectorName: t.sectorName, peopleAhead: Math.max(0, ahead || 0), estimatedMinutes: Math.max(0, ahead || 0) * 5,
    currentDisplay: current || "—", createdAt: t.createdAt };
}

async function configFor(db, tenantId) {
  const saved = await db.collection("customer_app_config").findOne({ tenantId });
  return { tenantId, businessName: saved?.businessName || "Mecan", branchId: saved?.branchId || "CENTRAL",
    sectors: Array.isArray(saved?.sectors) && saved.sectors.length ? saved.sectors : DEFAULT_SECTORS,
    banners: Array.isArray(saved?.banners) && saved.banners.length ? saved.banners : DEFAULT_BANNERS };
}

function page(tenantId) {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Mecan</title>
<style>:root{--red:#ef1010;--ink:#10243d;--bg:#f3f7fa}*{box-sizing:border-box}body{margin:0;background:var(--bg);font-family:system-ui,-apple-system,sans-serif;color:var(--ink);padding-bottom:calc(78px + env(safe-area-inset-bottom,0px))}.top{background:#fff;padding:calc(22px + env(safe-area-inset-top,0px)) 18px 14px;display:flex;align-items:center;gap:10px;position:sticky;top:0;z-index:3;box-shadow:0 2px 12px #1232}.logo{width:42px;height:42px;border-radius:50%;background:var(--red);color:#fff;font-size:30px;font-weight:900;display:grid;place-items:center}.top b{font-size:22px}.wrap{max-width:680px;margin:auto;padding:14px}.hero{position:relative;aspect-ratio:16/7;border-radius:20px;overflow:hidden;background:#dde5eb;box-shadow:0 8px 24px #1232}.hero img{width:100%;height:100%;object-fit:cover;display:none}.hero img.on{display:block}.dots{position:absolute;bottom:9px;left:0;right:0;text-align:center}.dots i{display:inline-block;width:8px;height:8px;border-radius:9px;background:#fff8;margin:3px}.dots i.on{width:22px;background:#fff}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}.card{border:0;border-radius:18px;background:#fff;padding:20px 12px;min-height:125px;box-shadow:0 5px 18px #1231;color:var(--ink);font-size:16px;font-weight:750}.card span{display:block;font-size:32px;margin-bottom:8px}.card.primary{background:var(--red);color:#fff}.section{background:#fff;border-radius:18px;padding:16px;margin-top:15px;box-shadow:0 5px 18px #1231}.section h2{font-size:19px;margin:0 0 12px}.sectors{display:grid;gap:9px}.sector{display:flex;justify-content:space-between;align-items:center;border:1px solid #dbe4eb;background:#fff;border-radius:13px;padding:13px;font-size:16px}.sector button,.action{border:0;border-radius:11px;background:var(--red);color:#fff;padding:10px 14px;font-weight:750}.ticket{text-align:center}.number{font-size:52px;font-weight:900;color:var(--red)}.ahead{font-size:20px;font-weight:750}.muted{color:#66788b;font-size:14px}.hide{display:none!important}.nav{position:fixed;bottom:0;left:0;right:0;height:calc(70px + env(safe-area-inset-bottom,0px));padding-bottom:env(safe-area-inset-bottom,0px);background:#fff;display:flex;justify-content:space-around;box-shadow:0 -3px 16px #1232;z-index:4}.nav button{border:0;background:none;color:#52667b;font-size:12px;font-weight:700}.nav span{display:block;font-size:23px}.toast{position:fixed;left:16px;right:16px;bottom:82px;background:#10243d;color:#fff;padding:13px;border-radius:12px;z-index:9}.loader{padding:30px;text-align:center}</style></head>
<body><header class="top"><div class="logo">m</div><div><b id="brand">Mecan</b><div class="muted">Tu comercio, más cerca</div></div></header><main class="wrap">
<section id="home"><div class="hero" id="hero"><div class="loader">Cargando ofertas…</div><div class="dots" id="dots"></div></div><div class="grid"><button class="card primary" onclick="scan()"><span>▣</span>Consultar precio</button><button class="card" onclick="showTurns()"><span>🎟️</span>Sacar turno</button><button class="card" onclick="showTicket()"><span>🔔</span>Mi turno</button><button class="card" onclick="location.href='https://www.mecan-sa.com.ar/'"><span>🛍️</span>Ver ofertas</button></div></section>
<section id="turns" class="section hide"><h2>¿Para qué sector necesitás turno?</h2><div class="sectors" id="sectors"></div></section>
<section id="my" class="section ticket hide"><div class="muted" id="sectorLabel"></div><div class="number" id="ticketNumber">—</div><div class="ahead" id="ahead"></div><p class="muted" id="estimate"></p><button class="action" onclick="refreshTicket()">Actualizar</button></section></main>
<nav class="nav"><button onclick="goHome()"><span>⌂</span>Inicio</button><button onclick="scan()"><span>▣</span>Escanear</button><button onclick="showTurns()"><span>🎟</span>Turnos</button><button onclick="showTicket()"><span>🔔</span>Mi turno</button></nav><div id="toast" class="toast hide"></div>
<script>const TENANT=${JSON.stringify(tenantId)};const API='/api/customer-app/'+encodeURIComponent(TENANT);const el=id=>document.getElementById(id);let cfg=null,timer=null;const newId=()=>window.crypto&&typeof window.crypto.randomUUID==='function'?window.crypto.randomUUID():Date.now()+'-'+Math.random();const installId=localStorage.asistoInstallId||(localStorage.asistoInstallId=newId());
function toast(s){let e=document.getElementById('toast');e.textContent=s;e.classList.remove('hide');setTimeout(()=>e.classList.add('hide'),3500)}function only(id){['home','turns','my'].forEach(x=>document.getElementById(x).classList.toggle('hide',x!==id))}function goHome(){only('home')}function scan(){location.href='/qr/'+encodeURIComponent(TENANT)+'?scan=1'}
async function init(){let r=await fetch(API+'/config');if(!r.ok)throw new Error('config');cfg=await r.json();el('brand').textContent=cfg.businessName;const hero=el('hero');hero.innerHTML=cfg.banners.map((x,i)=>'<img class="'+(i?'':'on')+'" src="'+x+'" alt="Oferta '+(i+1)+'">').join('')+'<div class="dots" id="dots">'+cfg.banners.map((_,i)=>'<i class="'+(i?'':'on')+'"></i>').join('')+'</div>';let n=0;setInterval(()=>{let a=[...hero.querySelectorAll('img')],d=[...hero.querySelectorAll('i')];if(!a.length)return;a[n].classList.remove('on');d[n].classList.remove('on');n=(n+1)%a.length;a[n].classList.add('on');d[n].classList.add('on')},4500);const sectors=el('sectors');sectors.innerHTML=cfg.sectors.map(s=>'<div class="sector"><b>'+s.name+'</b><button data-sector="'+s.id+'">Sacar turno</button></div>').join('');sectors.querySelectorAll('[data-sector]').forEach(button=>button.addEventListener('click',()=>takeTicket(button.dataset.sector)));registerPush();const view=new URLSearchParams(location.search).get('view');if(view==='turns')showTurns();else if(view==='ticket')showTicket()}
function showTurns(){only('turns')}function showTicket(){only('my');refreshTicket()}async function takeTicket(sectorId){let r=await fetch(API+'/tickets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sectorId,branchId:cfg.branchId,installId,pushToken:localStorage.asistoPushToken||''})});let x=await r.json();if(!r.ok)return toast(x.error||'No se pudo sacar el turno');localStorage.asistoTicketId=x.id;showTicket()}
async function refreshTicket(){let id=localStorage.asistoTicketId,number=el('ticketNumber'),label=el('sectorLabel'),ahead=el('ahead'),estimate=el('estimate');if(!id){number.textContent='—';label.textContent='Todavía no tenés un turno';ahead.textContent='';estimate.textContent='';return}let r=await fetch(API+'/tickets/'+encodeURIComponent(id)+'?installId='+encodeURIComponent(installId));let x=await r.json();if(!r.ok)return toast(x.error||'No se pudo actualizar');label.textContent=x.sectorName;number.textContent=x.displayNumber;if(x.status==='CALLED'){ahead.textContent='¡Es tu turno!';estimate.textContent='Acercate al sector.'}else if(x.status==='DONE'||x.status==='SKIPPED'){ahead.textContent='Turno finalizado';estimate.textContent='';clearInterval(timer)}else{ahead.textContent=x.peopleAhead===0?'Sos el próximo':x.peopleAhead+' persona'+(x.peopleAhead===1?'':'s')+' antes';estimate.textContent=x.estimatedMinutes?'Demora estimada: '+x.estimatedMinutes+' min':''}}
function registerPush(){function save(token){if(!token)return;localStorage.asistoPushToken=token;fetch(API+'/devices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({installId,pushToken:token})}).catch(()=>{})}window.addEventListener('asisto-push-token',e=>save(e.detail));if(window.AsistoNativePushToken)save(window.AsistoNativePushToken)}init().catch(()=>toast('No se pudo cargar la aplicación'));timer=setInterval(()=>{if(!document.getElementById('my').classList.contains('hide'))refreshTicket()},10000)</script></body></html>`;
}

function adminPage(tenantId) {
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Turnero ${tenantId}</title><style>body{font-family:system-ui;background:#eef3f7;color:#10243d;margin:0;padding:25px}.wrap{max-width:900px;margin:auto}.row{background:white;border-radius:15px;padding:18px;margin:12px 0;display:grid;grid-template-columns:1fr auto;gap:12px;box-shadow:0 4px 15px #1232}.num{font-size:30px;font-weight:900}.buttons{display:flex;gap:8px;flex-wrap:wrap}button{border:0;border-radius:9px;padding:11px 15px;background:#10243d;color:#fff;font-weight:700}.next{background:#e11}</style></head><body><div class="wrap"><h1>Turnero · ${tenantId}</h1><p>Atención por sector</p><div id="list">Cargando…</div></div><script>const T=${JSON.stringify(tenantId)},A='/api/customer-app-admin/'+encodeURIComponent(T);async function load(){let r=await fetch(A+'/state'),x=await r.json();list.innerHTML=x.sectors.map(s=>'<div class="row"><div><b>'+s.name+'</b><div class="num">'+(s.currentDisplay||'—')+'</div><small>'+s.waiting+' en espera</small></div><div class="buttons"><button class="next" onclick="act(\''+s.id+'\',\'next\')">Llamar siguiente</button><button onclick="act(\''+s.id+'\',\'finish\')">Finalizar</button></div></div>').join('')}async function act(s,a){await fetch(A+'/sectors/'+s+'/'+a,{method:'POST'});load()}load();setInterval(load,5000)</script></body></html>`;
}

function mountCustomerApp(app) {
  app.use("/api/customer-app", express.json({ limit: "32kb" }));
  app.use("/api/customer-app-admin", express.json({ limit: "32kb" }));
  app.get("/customer-app/:tenant", (req, res) => { const t = tenant(req.params.tenant); if (!t) return res.status(400).send("Dominio inválido"); res.type("html").send(page(t)); });
  app.get("/api/customer-app/:tenant/config", async (req, res) => { try { const t=tenant(req.params.tenant); res.json(await configFor(await getDb(), t)); } catch(e){ res.status(500).json({error:"No se pudo cargar la aplicación"}); } });
  app.post("/api/customer-app/:tenant/devices", async (req,res)=>{ try{const t=tenant(req.params.tenant),installId=clean(req.body.installId,120),pushToken=clean(req.body.pushToken,500);if(!installId||!pushToken)return res.status(400).json({error:"Datos incompletos"});await (await getDb()).collection("customer_app_devices").updateOne({tenantId:t,installId},{$set:{pushToken,updatedAt:new Date()}},{upsert:true});res.json({ok:true})}catch(e){res.status(500).json({error:"No se pudo registrar el dispositivo"})} });
  app.post("/api/customer-app/:tenant/tickets", async (req,res)=>{try{const t=tenant(req.params.tenant),installId=clean(req.body.installId,120),branchId=clean(req.body.branchId||"CENTRAL",40),sectorId=clean(req.body.sectorId,40);if(!t||!installId||!sectorId)return res.status(400).json({error:"Datos incompletos"});const db=await getDb(),cfg=await configFor(db,t),sector=cfg.sectors.find(s=>s.id===sectorId);if(!sector)return res.status(400).json({error:"Sector inválido"});const day=dayKey(),tickets=db.collection("queue_tickets");let doc=await tickets.findOne({tenantId:t,dayKey:day,branchId,sectorId,installId,status:{$in:["WAITING","CALLED"]}});if(!doc){const key=[t,day,branchId,sectorId].join(":"),counter=await db.collection("queue_counters").findOneAndUpdate({_id:key},{$inc:{sequence:1},$setOnInsert:{tenantId:t,dayKey:day,branchId,sectorId}},{upsert:true,returnDocument:"after"});const number=counter.sequence,now=new Date();doc={tenantId:t,dayKey:day,branchId,sectorId,sectorName:sector.name,prefix:sector.prefix,number,displayNumber:sector.prefix+String(number).padStart(3,"0"),status:"WAITING",installId,createdAt:now,updatedAt:now};const out=await tickets.insertOne(doc);doc._id=out.insertedId}const ahead=await tickets.countDocuments({tenantId:t,dayKey:day,branchId,sectorId,status:"WAITING",number:{$lt:doc.number}});res.json(ticketView(doc,ahead))}catch(e){console.error("[customer-app] ticket",e);res.status(500).json({error:"No se pudo generar el turno"})}});
  app.get("/api/customer-app/:tenant/tickets/:id",async(req,res)=>{try{const t=tenant(req.params.tenant),installId=clean(req.query.installId,120);if(!ObjectId.isValid(req.params.id))return res.status(404).json({error:"Turno inexistente"});const db=await getDb(),tickets=db.collection("queue_tickets"),doc=await tickets.findOne({_id:new ObjectId(req.params.id),tenantId:t,installId});if(!doc)return res.status(404).json({error:"Turno inexistente"});const ahead=await tickets.countDocuments({tenantId:t,dayKey:doc.dayKey,branchId:doc.branchId,sectorId:doc.sectorId,status:"WAITING",number:{$lt:doc.number}}),state=await db.collection("queue_state").findOne({_id:[t,doc.branchId,doc.sectorId].join(":")});res.json(ticketView(doc,ahead,state?.currentDisplay))}catch(e){res.status(500).json({error:"No se pudo consultar el turno"})}});
  app.get("/ui/turnero/:tenant",(req,res)=>res.type("html").send(adminPage(tenant(req.params.tenant))));
  app.get("/api/customer-app-admin/:tenant/state",async(req,res)=>{try{const t=tenant(req.params.tenant),db=await getDb(),cfg=await configFor(db,t),day=dayKey();const sectors=await Promise.all(cfg.sectors.map(async s=>{const state=await db.collection("queue_state").findOne({_id:[t,cfg.branchId,s.id].join(":")}),waiting=await db.collection("queue_tickets").countDocuments({tenantId:t,dayKey:day,branchId:cfg.branchId,sectorId:s.id,status:"WAITING"});return {...s,waiting,currentDisplay:state?.currentDisplay||""}}));res.json({sectors})}catch(e){res.status(500).json({error:"Error de turnero"})}});
  app.post("/api/customer-app-admin/:tenant/sectors/:sector/:action",async(req,res)=>{try{const t=tenant(req.params.tenant),sectorId=clean(req.params.sector,40),action=clean(req.params.action,20),db=await getDb(),cfg=await configFor(db,t),key=[t,cfg.branchId,sectorId].join(":"),tickets=db.collection("queue_tickets");if(action==="finish"){await tickets.updateMany({tenantId:t,branchId:cfg.branchId,sectorId,status:"CALLED"},{$set:{status:"DONE",updatedAt:new Date()}});await db.collection("queue_state").updateOne({_id:key},{$set:{currentDisplay:"",updatedAt:new Date()}},{upsert:true})}else if(action==="next"){await tickets.updateMany({tenantId:t,branchId:cfg.branchId,sectorId,status:"CALLED"},{$set:{status:"DONE",updatedAt:new Date()}});const next=await tickets.findOneAndUpdate({tenantId:t,dayKey:dayKey(),branchId:cfg.branchId,sectorId,status:"WAITING"},{$set:{status:"CALLED",calledAt:new Date(),updatedAt:new Date()}},{sort:{number:1},returnDocument:"after"});await db.collection("queue_state").updateOne({_id:key},{$set:{currentDisplay:next?.displayNumber||"",currentTicketId:next?._id||null,updatedAt:new Date()}},{upsert:true})}else return res.status(400).json({error:"Acción inválida"});res.json({ok:true})}catch(e){console.error("[turnero]",e);res.status(500).json({error:"Error de turnero"})}});
}

module.exports = { mountCustomerApp, DEFAULT_SECTORS, dayKey };
