// Asisto | Version: 5.00.158 | Fecha: 2026-09-18
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

function renderRestaurantPage({ tenant, token, name, table, logoUrl }) {
  const base = `/api/public/resto/${encodeURIComponent(tenant)}/${encodeURIComponent(token)}`;
  const logo = typeof logoUrl === 'string' && (/^https:\/\//i.test(logoUrl) || logoUrl.startsWith('/static/')) ? logoUrl : '/static/restaurant_logo_example.svg';
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Carta · ${escapeHtml(name)}</title><link rel="stylesheet" href="/static/restaurant_menu.css?v=5.00.158"></head><body data-base="${escapeHtml(base)}"><header><div class="hero"><img class="logo" src="${escapeHtml(logo)}" alt="Logo de ${escapeHtml(name)}"><div><p class="eyebrow">Bienvenidos a</p><h1>${escapeHtml(name)}</h1><p class="table-label">Mesa ${escapeHtml(table)} · Carta digital</p></div></div></header><main><div class="intro"><p>Elegí algo rico, armá tu pedido y consultanos lo que necesites.</p></div><div class="actions"><button id="call">🙋 Llamar al mozo</button><button id="bill">🧾 Pedir la cuenta</button></div><p id="msg" role="status" aria-live="polite"></p><h2>Explorá la carta</h2><p class="hint">Tocá una categoría para ver sus platos y bebidas.</p><div id="menu"></div><section class="box" id="pedido"><h2>Tu pedido <span id="cart-count">(0)</span></h2><div id="cart"></div><label for="note">Indicaciones para cocina</label><textarea id="note" rows="3" placeholder="Por ejemplo, sin cebolla"></textarea><button id="order">Enviar pedido</button></section><section class="box"><h2>¿Qué se te antoja?</h2><p>Preguntanos por ingredientes, opciones o combinaciones para tu mesa.</p><label for="question">Tu consulta</label><input id="question" maxlength="500" placeholder="Sugerime una cena con bebida"/><button id="ask">✨ Preguntar por la carta</button><p id="answer" role="status" aria-live="polite"></p><small>Informá alergias al personal antes de pedir.</small></section></main><div id="toast" role="status" aria-live="polite"></div><script src="/static/restaurant_menu.js?v=5.00.158" defer></script></body></html>`;
}

module.exports = { renderRestaurantPage };
