// Asisto | Version: 5.00.160 | Fecha: 2026-09-18
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));

function renderRestaurantPage({ tenant, token, name, table, logoUrl }) {
  const base = `/api/public/resto/${encodeURIComponent(tenant)}/${encodeURIComponent(token)}`;
  const logo = typeof logoUrl === 'string' && (/^https:\/\//i.test(logoUrl) || logoUrl.startsWith('/static/')) ? logoUrl : '/static/restaurant_logo_example.svg';
  const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Carta · ${escapeHtml(name)}</title><link rel="stylesheet" href="/static/restaurant_menu.css?v=5.00.160"></head><body data-base="${escapeHtml(base)}"><header><div class="hero"><img class="logo" src="${escapeHtml(logo)}" alt="Logo de ${escapeHtml(name)}"><div><p class="eyebrow">Bienvenidos a</p><h1>${escapeHtml(name)}</h1><p class="table-label">Mesa ${escapeHtml(table)} · Carta digital</p></div></div></header><main><div class="intro"><p>Elegí algo rico, armá tu pedido y consultanos lo que necesites.</p></div><div class="actions"><button id="call">🙋 Llamar al mozo</button><button id="bill">🧾 Pedir la cuenta</button></div><p id="msg" role="status" aria-live="polite"></p><h2>Explorá la carta</h2><p class="hint">Tocá una categoría para ver sus platos y bebidas.</p><div id="menu"></div><section class="box" id="pedido"><h2>Tu pedido <span id="cart-count">(0)</span></h2><div id="cart"></div><label for="note">Indicaciones para cocina</label><textarea id="note" rows="3" placeholder="Por ejemplo, sin cebolla"></textarea><button id="order">Enviar pedido</button></section><section class="box"><h2>¿Qué se te antoja?</h2><p>Preguntanos por ingredientes, opciones o combinaciones para tu mesa.</p><label for="question">Tu consulta</label><input id="question" maxlength="500" placeholder="Sugerime una cena con bebida"/><button id="ask">✨ Preguntar por la carta</button><p id="answer" role="status" aria-live="polite"></p><small>Informá alergias al personal antes de pedir.</small></section></main><div id="toast" role="status" aria-live="polite"></div><script src="/static/restaurant_menu.js?v=5.00.160" defer></script></body></html>`;
  return html.replaceAll('5.00.160', '5.00.160')
    .replace('<button id="call">', '<button id="call" hidden>')
    .replace('<button id="bill">', '<button id="bill" hidden>')
    .replace('<section class="box" id="pedido">', '<section class="box" id="pedido" hidden>')
    .replace('<section class="box"><h2>¿Qué se te antoja?</h2>', '<section class="box" id="guestAiSection" hidden><h2>¿Qué se te antoja?</h2>')
    .replace('</main>', `<section class="box" id="guestAccount" hidden><h2>Tu mesa, al día</h2><div id="guestOrderStatus" aria-live="polite"></div><div id="splitBill" hidden><label for="splitGuests">Dividir el saldo entre</label><input id="splitGuests" type="number" min="1" max="100" value="2"><p id="splitResult"></p><small>Es una estimación entre comensales. No registra pagos.</small></div></section><section class="box" id="guestPayment" hidden><h2>Pagá a tu manera</h2><button id="payMercadoPago" type="button">Mercado Pago · próximamente</button><p id="paymentInfo" role="status">Por ahora, coordiná el pago con el personal.</p></section><section class="box guest-notifications" hidden><h2>Mensajes de tu mesa</h2><p>Si el restaurante te envía un aviso, aparecerá acá. Podés activar los avisos del navegador mientras mantenés la carta abierta.</p><button id="enableGuestAlerts" type="button">Activar avisos</button><p id="guestAlertStatus" role="status" aria-live="polite"></p><div id="guestMessages"></div></section></main>`);
}

module.exports = { renderRestaurantPage };
