// Asisto | Version: 5.00.169 | Fecha: 2026-09-19
const test=require('node:test'),assert=require('node:assert/strict');
const {MongoMemoryServer}=require('mongodb-memory-server');
const {MongoClient,ObjectId}=require('mongodb');
const {mutateTable,addGuestOrder}=require('../restaurant_operations');
const {joinVisit,validateVisit}=require('../restaurant_visit');
const {validateRestaurantConfig}=require('../restaurant_config');
test('QR: código, credencial, vencimiento, cierre/reapertura y concurrencia no reabren visitas',async t=>{
 const mongo=await MongoMemoryServer.create(),client=await MongoClient.connect(mongo.getUri()),db=client.db('visit_security');
 t.after(async()=>{await client.close();await mongo.stop();});
 const id=new ObjectId(),visitorId='12345678-1234-4123-8123-123456789abc',actor={name:'test',origin:'operator'},catalog=[{id:new ObjectId().toString(),nombre:'Agua',precio:100,disponible:true}];
 await db.collection('restaurant_tables').insertOne({_id:id,tenantId:'RES',active:true,label:'1'});
 const ctx=async()=>({db,config:{},table:await db.collection('restaurant_tables').findOne({_id:id})});
 const act=(a,p={})=>mutateTable(db,'RES',String(id),a,p,catalog,actor);
 const body={visitorId,requestId:'one',items:[{id:catalog[0].id,quantity:1}]};
 await assert.rejects(addGuestOrder(await ctx(),body,catalog),e=>e.status===403);
 const opened=await act('open');
 await assert.rejects(joinVisit(await ctx(),{visitorId,code:'wrong'}),/código/);
 const visit=await joinVisit(await ctx(),{visitorId,code:opened.service.visitCode});
 body.visitToken=visit.token;
 await assert.rejects(addGuestOrder(await ctx(),{...body,visitorId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'},catalog),e=>e.status===403);
 const first=await addGuestOrder(await ctx(),body,catalog);
 assert.equal((await ctx()).table.service.orders[0].status,'awaiting_confirmation');
 assert.equal((await addGuestOrder(await ctx(),body,catalog)).id,first.id);
 await assert.rejects(addGuestOrder(await ctx(),{...body,requestId:'too-fast'},catalog),e=>e.status===429);
 await assert.rejects(act('orderStatus',{orderId:first.id,status:'preparing'}),/Confirmá/);
 await act('orderStatus',{orderId:first.id,status:'cancelled',reason:'prueba'});
 await act('close');
 for(const action of ['addOrder','guestSignal'])await assert.rejects(mutateTable(db,'RES',String(id),action,{...body,type:'call'},catalog,{...actor,origin:'guest',visitorId,visitToken:visit.token}),e=>e.status===403);
 const reopened=await act('open');assert.notEqual(reopened.service.id,opened.service.id);
 await assert.rejects(addGuestOrder(await ctx(),body,catalog),e=>e.status===403);
 const next=await joinVisit(await ctx(),{visitorId,code:reopened.service.visitCode});
 await act('rotateVisit');
 await assert.rejects(addGuestOrder(await ctx(),{...body,visitToken:next.token,requestId:'rotated'},catalog),e=>e.status===403);
 const rotated=(await ctx()).table;
 const current=await joinVisit(await ctx(),{visitorId,code:rotated.service.visitCode});
 await db.collection('restaurant_tables').updateOne({_id:id},{$set:{'service.visitStartedAt':new Date(Date.now()-5*3600000)}});
 await assert.rejects(addGuestOrder(await ctx(),{...body,visitToken:current.token,requestId:'expired'},catalog),e=>e.status===403);
 await act('rotateVisit');const fresh=await joinVisit(await ctx(),{visitorId,code:(await ctx()).table.service.visitCode});
 const stale=await ctx();await act('close');
 await assert.rejects(addGuestOrder(stale,{...body,visitToken:fresh.token,requestId:'stale-read'},catalog),e=>e.status===403);
 assert.equal((await ctx()).table.service.status,'closed');
 await act('open');const noCode=await ctx();noCode.config={restaurant_visit_code_required:false,restaurant_order_confirmation_required:false};
 const unrestricted=await joinVisit(noCode,{visitorId});
 await addGuestOrder(noCode,{...body,visitToken:unrestricted.token,requestId:'no-confirm'},catalog);
 assert.equal((await ctx()).table.service.orders[0].status,'received');
});
test('configuración de visita rechaza duración inválida y banderas no booleanas',()=>{
 for(const hours of [0,25,1.5,'4',null])assert.throws(()=>validateRestaurantConfig({restaurant_visit_hours:hours}),/entero/);
 for(const name of ['restaurant_visit_code_required','restaurant_order_confirmation_required'])assert.throws(()=>validateRestaurantConfig({[name]:'false'}),/true o false/);
 validateRestaurantConfig({restaurant_visit_hours:4,restaurant_visit_code_required:true,restaurant_order_confirmation_required:false});
});
