// Asisto | Version: 5.00.079 | Fecha: 2026-09-09
const {chromium}=require(process.env.ASISTO_PLAYWRIGHT_MODULE || 'playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.ASISTO_CHROME_PATH ? {executablePath:process.env.ASISTO_CHROME_PATH} : {})});const page=await browser.newPage({viewport:{width:410,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('https://fixture.local/**',route=>{const file=path.basename(new URL(route.request().url()).pathname);route.fulfill({body:fs.readFileSync(path.join(__dirname,'../extensions/whatsapp-support',file)),contentType:file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':'application/javascript'});});
await page.addInitScript(()=>{
window.fixtureCalls=[];let revision=1;const fields={subject:'Consulta sobre stock y carga de ventas',contact:'Eugenio · Administración',company:'Empresa de prueba',description:'El contacto solicita revisar el stock de cereales para cargar una venta. Se indicó revisar la configuración y enviar los datos pendientes.',status:'En Proceso',category:'Soporte Remoto',errorType:'Consulta / Capacitacion',channel:'WhatsApp'};
const metadata={pipelines:[{id:'p',label:'Soporte',stages:[{id:'s',label:'En Proceso'}]}],properties:[['category','Categoría','Soporte Remoto'],['error','Error tipo','Consulta / Capacitacion'],['channel','Vía de contacto','WhatsApp']].map(([name,label,value])=>({name,label,type:'enumeration',options:[{value,label:value}]}))};
window.chrome={runtime:{sendMessage:async m=>{fixtureCalls.push(m);switch(m.action){case'SESSION':return{data:{tenantId:'ALSO',userId:'a',username:'admin',choices:{status:['Nuevo','En Proceso'],category:['Soporte Remoto'],errorType:['Consulta / Capacitacion'],channel:['WhatsApp']}}};case'INDEX':return{data:{owner:'ALSO:a',chats:[{jid:'1@lid',name:fields.contact,count:1}]}};case'DRAFTS':return{data:[{id:'d',subject:fields.subject}]};case'DETAIL':return{data:{id:'d',revision,fields,source:{description:fields.description},mode:'approval'}};case'SAVE':Object.assign(fields,m.fields);return{data:{revision:++revision}};case'HUBSPOT':return{data:{configured:true,portalId:'123',metadata}};case'PUBLISH':return{data:{ticketId:'99',portalId:'123',revision:++revision}};}}},tabs:{query:async()=>[{id:1}]},storage:{session:{get:async()=>({'selection-1':{jid:'1@lid'}})},local:{get:async()=>({}),set:async()=>{}},onChanged:{addListener:()=>{}}}};
});
await page.goto('https://fixture.local/panel.html');await page.locator('#field-contact').waitFor();assert.equal(await page.locator('#field-contact').inputValue(),'Eugenio · Administración');
assert.equal(await page.locator('#field-status').evaluate(element=>element.tagName),'SELECT');assert.equal(await page.locator('#field-category').evaluate(element=>element.tagName),'SELECT');
await page.locator('#field-subject').fill('Revisar stock de cereales');await page.locator('#editor button[type=submit]').click();await page.locator('#notice').filter({hasText:'Cambios guardados'}).waitFor();
await page.locator('#setup').click();await page.locator('#hubspot').waitFor({state:'visible'});await page.locator('#pipeline').selectOption('p');assert.equal(await page.locator('#stage').inputValue(),'s');assert.equal(await page.locator('#value-category').inputValue(),'Soporte Remoto');
if(process.env.ASISTO_EXTENSION_SCREENSHOT) await page.screenshot({path:process.env.ASISTO_EXTENSION_SCREENSHOT,fullPage:true});
await page.locator('#publish').click();await page.locator('#notice').filter({hasText:'Ticket 99 guardado'}).waitFor();assert.equal(await page.locator('#ticket a').getAttribute('href'),'https://app.hubspot.com/contacts/123/record/0-5/99');
const count=await page.evaluate(()=>fixtureCalls.filter(c=>c.action==='PUBLISH').length);assert.equal(count,1);
await page.goto('about:blank');await page.setContent('<div id="pane-side"><div role="row"><span dir="auto" title="Juan">Juan</span></div><div role="row"><span title="Repetido">Repetido</span></div></div>');
await page.evaluate(()=>{window.opened=[];window.chrome={runtime:{id:'a',sendMessage:async m=>{if(m.action==='INDEX')return{data:{chats:[{jid:'1@lid',name:'Juan',count:2},{jid:'2@lid',name:'Repetido',count:1},{jid:'3@lid',name:'Repetido',count:1}]}};opened.push(m);return{ok:true};}}};});
await page.addScriptTag({path:path.join(__dirname,'../extensions/whatsapp-support/matcher.js')});await page.addScriptTag({path:path.join(__dirname,'../extensions/whatsapp-support/content.js')});
await page.locator('.asisto-task-badge').waitFor();assert.equal(await page.locator('.asisto-task-badge').count(),1);await page.locator('.asisto-task-badge').click();assert.equal(await page.evaluate(()=>opened[0].jid),'1@lid');
await page.locator('span[title="Juan"]').evaluate(el=>{el.title='Otro';el.textContent='Otro';});await page.waitForTimeout(300);assert.equal(await page.locator('.asisto-task-badge').count(),0);
await page.evaluate(()=>{document.body.insertAdjacentHTML('beforeend','<div id="main"><header><span title="Juan">Juan</span></header><div data-id="false_1@lid_MESSAGE"></div></div>');});
await page.locator('#main .asisto-task-badge').waitFor();assert.equal(await page.evaluate(()=>opened.filter(m=>m.action==='CONTACT'&&m.jid==='1@lid'&&m.name==='Juan').length),1);
assert.equal(await page.evaluate(()=>opened.filter(m=>m.action==='OPEN').length),1);
assert.deepEqual(errors,[]);console.log('PASS panel load/edit/save/mapping/publish; contact badge click; ambiguous names; recycled row cleanup; visible contact sync without auto-opening; no page errors');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
